version: '2'

services:
  mysqld:
    image: mysql:5.7
    # Uncomment if you want to expose the MySQL server to your host, e.g. for using a database management GUI application
    # ports:
    # - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  markdown:
    build: 'src/athene2-editor-server'

  athene2:
    build: .
    links:
      - mysqld:mysqld
      - markdown:markdown
    ports:
      - '4567:80'
    volumes:
      # For macOS, add `:delegated` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./phpunit.xml:/var/www/html/phpunit.xml
      - ./src/config:/var/www/html/src/config
      - ./src/lang:/var/www/html/src/lang
      - ./src/module:/var/www/html/src/module
      - ./src/public:/var/www/html/src/public
      - ./src/test:/var/www/html/src/test
      - ./src/vendor:/var/www/html/src/vendor
    environment:
      - PHP_ENV=development
  # Uncomment if you want PhpMyAdmin on localhost:8080
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - mysqld:db
  #   ports:
  #     - '8080:80'


  hydra:
    image: oryd/hydra:v1.0.0-rc.6_oryOS.10
    ports:
    - "4444:4444"
    - "4445:4445"
    command:
      serve all --dangerous-force-http
    environment:
    - LOG_LEVEL=debug
    - OAUTH2_SHARE_ERROR_DEBUG=1
    - OAUTH2_ISSUER_URL=http://localhost:4444
    - OAUTH2_LOGIN_URL=http://localhost:4567/auth/hydra/login
    - OAUTH2_CONSENT_URL=http://localhost:4567/auth/hydra/consent
    - DATABASE_URL=memory
    - SYSTEM_SECRET=youReallyNeedToChangeThis
    - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
    - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
    restart: unless-stopped