version: '2'

services:

  mysqld:
    image: mysql:5.7
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  athene2:
    build: .
    links:
      - mysqld:mysqld
    ports:
      - "4567:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_ENV=development