version: '3.4'

services:
  mysql:
    image: mysql:5.7
    # Uncomment if you want to expose the MySQL server to your host, e.g. for using a database management GUI application
    # ports:
    # - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  legacy-editor-renderer:
    image: serlo/legacy-editor-renderer:0.0.0

  editor-renderer:
    image: serlo/editor-renderer:0.0.0

  composer:
    image: composer:1.8
    volumes:
      # For macOS, add `:cached` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./src/vendor:/app/src/vendor

  composer-dev-tools:
    image: composer:1.8
    volumes:
      # For macOS, add `:cached` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./dev-tools/composer.json:/app/composer.json
      - ./dev-tools/composer.lock:/app/composer.lock
      - ./dev-tools/vendor:/app/vendor

  httpd:
    build:
      context: .
      dockerfile: docker/httpd/Dockerfile
      target: base
    ports:
      - '4567:80'
    volumes:
      # For macOS, add `:delegated` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./src/public:/usr/local/apache2/htdocs/src/public:delegated
    environment:
      - PHP_HOST=php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
    volumes:
      # For macOS, add `:delegated` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./dev-tools/vendor:/usr/local/apache2/htdocs/dev-tools/vendor
      - ./php-cs-fixer.config.php:/usr/local/apache2/htdocs/php-cs-fixer.config.php
      - ./phpunit.xml:/usr/local/apache2/htdocs/phpunit.xml
      - ./src/config:/usr/local/apache2/htdocs/src/config
      - ./src/lang:/usr/local/apache2/htdocs/src/lang
      - ./src/module:/usr/local/apache2/htdocs/src/module
      - ./src/public:/usr/local/apache2/htdocs/src/public
      - ./src/test:/usr/local/apache2/htdocs/src/test
      - ./src/vendor:/usr/local/apache2/htdocs/src/vendor
      - ./src/init_autoloader.php:/usr/local/apache2/htdocs/src/init_autoloader.php
  # Uncomment if you want PhpMyAdmin on localhost:8080
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - mysqld:db
  #   ports:
  #     - '8080:80'
