version: '2'

services:
  mysqld:
    image: mysql:5.7
    # Uncomment if you want to expose the MySQL server to your host, e.g. for using a database management GUI application
    # ports:
    # - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  markdown:
    build: 'src/athene2-editor-server'

  composer:
    image: composer:1.8
    volumes:
      # For macOS, add `:cached` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./src/vendor:/app/src/vendor

  composer-dev-tools:
    image: composer:1.8
    volumes:
      # For macOS, add `:cached` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./dev-tools/composer.json:/app/composer.json
      - ./dev-tools/composer.lock:/app/composer.lock
      - ./dev-tools/vendor:/app/vendor

  athene2:
    build: .
    links:
      - mysqld:mysqld
      - markdown:markdown
    ports:
      - '4567:80'
    volumes:
      # For macOS, add `:delegated` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./dev-tools/vendor:/var/www/html/dev-tools/vendor
      - ./php-cs-fixer.config.php:/var/www/html/php-cs-fixer.config.php
      - ./phpunit.xml:/var/www/html/phpunit.xml
      - ./src/config:/var/www/html/src/config
      - ./src/lang:/var/www/html/src/lang
      - ./src/module:/var/www/html/src/module
      - ./src/public:/var/www/html/src/public
      - ./src/test:/var/www/html/src/test
      - ./src/vendor:/var/www/html/src/vendor
    environment:
      - PHP_ENV=development
  # Uncomment if you want PhpMyAdmin on localhost:8080
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - mysqld:db
  #   ports:
  #     - '8080:80'
